apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter-app
  name: jupyter-svc
  namespace: jupyter
spec:
  clusterIP: 10.102.10.182
  clusterIPs:
  - 10.102.10.182
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-pods
  sessionAffinity: None
  type: NodePort

