apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    metadata:
      name: my-jop-pod
    spec:
      containers:
      - name: my-busybox
        image: busybox
        command:
        - "bin/sh"
        - "-c"
        - "for i in 1 2; do echo Lucky number $1 = $((1 + RANDOM % 70)); done"
      restartPolicy: Never
